### ISSUE TITLE
SCSS 的 Import，Mixins 和 Extend

### ISSUE THREAD

**Issue by liunaijia** [liunaijia/blog#4]
Saas 的参考：http://sass-lang.com/guide

## Import partial css

为了 css 文件的可维护性，有时需要将一个大的文件分割成多个小文件，并且在某个文件中导入其它文件中的样式定义，这时可以用`@import`指令。

首先创建partials，文件名以下划线开头，告诉 scss preprocessor 不要单独编译这个文件，因为它会被包含到导入它的文件中。

```scss
// _reset.scss

html,
body,
ul,
ol {
   margin: 0;
  padding: 0;
}

```

然后再另外一个文件中引用它：

```scss
// base.scss

@import 'reset';

body {
  font: 100% Helvetica, sans-serif;
  background-color: #efefef;
}
```

这样编译后的结果是：

```css
html, body, ul, ol {
  margin: 0;
  padding: 0;
}

body {
  font: 100% Helvetica, sans-serif;
  background-color: #efefef;
}
```

## Mixins

Mixin 就像方法：通过`@mixin`关键字定义，通过`@include`关键字调用，更棒的是还可以传递参数。

定义并调用一个mixin：

```scss
@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
     -moz-border-radius: $radius;
      -ms-border-radius: $radius;
          border-radius: $radius;
}

.box { @include border-radius(10px); }
```

生成的代码是：

```css
.box {
  -webkit-border-radius: 10px;
  -moz-border-radius: 10px;
  -ms-border-radius: 10px;
  border-radius: 10px;
}
```

## Extend

顾名思义 Extend 就想代码中的继承，通过`@extend`关键字继承一个样式，然后可以重写其中的样式定义：

```scss
.message {
  border: 1px solid #ccc;
  padding: 10px;
  color: #333;
}

.success {
  @extend .message;
  border-color: green;
}

.error {
  @extend .message;
  border-color: red;
}

.warning {
  @extend .message;
  border-color: yellow;
}
```

生成的代码为：

```css
.message, .success, .error, .warning {
  border: 1px solid #cccccc;
  padding: 10px;
  color: #333;
}

.success {
  border-color: green;
}

.error {
  border-color: red;
}

.warning {
  border-color: yellow;
}
```

## Mixins 和 Extend 的选择 

选择 Mixins。看起来 Extend 方法生成的 css 代码更少，实际上也是如此，但生产环境中 css 都经过了 gzip 压缩，使用这两种方法编写的样式文件经过压缩后尺寸差别不大。此外，由于 mixin 方式把某个 class 样式定义所需要的代码都集中到一个地方，浏览器处理效率更高。

[这篇文章](https://tech.bellycard.com/blog/sass-mixins-vs-extends-the-data/)提到了两种方式的代码量、压缩后的文件尺寸和处理效率的性能测试。
